Repository edugator-cise/edugator-staff-frontend, pull requests merged in 2021-11, with the labels that each got.

#71 Adrian salazar/grading requests
  src/app/common/rootReducer.ts
  src/app/common/rootSaga.ts
  src/pages/grading/GradingDialog.sagas.ts
  src/pages/grading/GradingDialog.slice.ts
  src/pages/grading/components/GradingDialog.tsx
  src/pages/grading/components/GradingDropArea.tsx
  src/pages/grading/types.ts
  src/pages/modules/components/ModuleAccordion.tsx
  src/pages/modules/components/ModuleMenu.tsx
  src/shared/GenericDialog.tsx
Labels: enhancement

#74 Fixed the button bug
  src/pages/modules/components/ModuleAccordion.tsx
Labels: bug

#75 Marcgabe15/setup linking
  src/App.tsx
  src/pages/CodeEditor/CodeEditor.sagas.ts
  src/pages/CodeEditor/CodeEditorPage.tsx
  src/pages/CodeEditor/CodeEditorSlice.ts
  src/pages/CodeEditor/SideNav.tsx
  src/pages/CodeEditor/__tests__/CodeEditor.reducer.spec.ts
  src/pages/CodeEditor/types.ts
  src/pages/LandingPage/LandingHome.tsx
  src/shared/Routes.constants.tsx
  src/shared/VerticalNavigation.tsx
Labels: enhancement

#80 Joshuadargan/notfound
  package-lock.json
  src/App.tsx
  src/assets/EdugatorNotFound.png
  src/pages/NotFound/NotFoundPage.tsx
  src/shared/Routes.constants.tsx
  src/shared/VerticalNavigation.tsx
Labels: enhancement

#96 Added a message for empty modules
  src/pages/modules/components/ModuleAccordion.tsx
Labels: enhancement

#101 Validate add/edit module, fix alert bug, make alert dismissable, and sort modules
  src/pages/modules/ModulesPage.sagas.ts
  src/pages/modules/ModulesPage.slice.ts
  src/pages/modules/components/ModuleDialog.tsx
  src/pages/modules/components/ModulesSnackbar.tsx
  src/shared/LayoutContainer.tsx
Labels: bug, enhancement

#100 centered the login page loading and error message
  src/pages/Login/LoginPage.tsx
Labels: bug

#102 Test Case Editor bug fix - no empty test cases
  src/pages/ProblemEditor/TestEditor/TestEditorForm.tsx
Labels: bug

#105 Adrian salazar/admin accounts dashboard
  src/App.tsx
  src/app/common/rootReducer.ts
  src/app/common/rootSaga.ts
  src/pages/accounts/AdminAccountsPage.sagas.ts
  src/pages/accounts/AdminAccountsPage.slice.ts
  src/pages/accounts/AdminAccountsPage.tsx
  src/pages/accounts/components/AccountDialog.tsx
  src/pages/accounts/components/AccountInfo.tsx
  src/pages/accounts/components/AccountInfoEdit.tsx
  src/pages/accounts/components/AccountSnackbar.tsx
  src/pages/accounts/components/AccountsTable.tsx
  src/pages/accounts/components/AdminActions.tsx
  src/pages/accounts/components/DashboardProgress.tsx
  src/pages/accounts/components/NewAccountDialog.tsx
  src/pages/accounts/components/index.ts
  src/pages/accounts/types.ts
  src/pages/grading/GradingDialog.slice.ts
  src/pages/modules/ModulesPage.sagas.ts
  src/pages/modules/ModulesPage.slice.ts
  src/pages/modules/ModulesPage.tsx
  src/pages/modules/components/DeleteDialog.tsx
  src/pages/modules/components/ModuleDialog.tsx
  src/pages/modules/types.ts
  src/shared/GenericDialog.tsx
  src/shared/Routes.constants.tsx
  src/shared/types.ts
Labels: enhancement

#119 Joshuadargan/required visible test case
  src/pages/ProblemEditor/TestEditor/TestCase.tsx
  src/pages/ProblemEditor/TestEditor/TestEditorForm.tsx
  src/shared/ConfirmDelete.tsx
Labels: bug, enhancement

#145 Adrian salazar/accounts functionality
  src/pages/accounts/AdminAccountsPage.sagas.ts
  src/pages/accounts/AdminAccountsPage.slice.ts
  src/pages/accounts/AdminAccountsPage.tsx
  src/pages/accounts/__tests__/AdminAccountsPage.slice.spec.ts
  src/pages/accounts/components/AccountInfoEdit.tsx
  src/pages/accounts/components/AccountsTable.tsx
  src/pages/accounts/components/NewAccountDialog.tsx
  src/pages/accounts/components/accountDialog/AccountDialog.tsx
  src/pages/accounts/components/accountDialog/AccountInfo.tsx
  src/pages/accounts/components/accountDialog/AccountInfoEdit.tsx
  src/pages/accounts/components/accountDialog/AdminActions.tsx
  src/pages/accounts/components/index.ts
  src/pages/accounts/types.ts
  src/pages/modules/components/ModuleDialog.tsx
  src/shared/utils.ts
Labels: enhancement
